cookie:
  expiry_days: 30
  key: sample_signature_key
  name: sample_cookie_name
credentials:
  usernames:
    malhajae:
      email: sadada
      name: adasda
      password: '123456'
    malhajar:
      email: malhajar@example.com
      name: mohamad
      password: $2b$12$Jq01BZHmkVrAgM.j50XePON9zQcvDiEC1/g3tvtiLTqVFBaoc3yuS
    malhajar12:
      email: sad
      name: sada
      password: $2b$12$x0tBWGLcsoU3GLNvGgWHmO4H.eFZhoqbecEFz/YdMxtja52bcif6a
    malhajar123:
      email: adfasd
      name: sdasda
      password: $2b$12$TAYJ7ElFyGshON1.ox30ue/qsvnqkgBqegpnsG2zWHTaIR3ub0Zgm
    malhajar1234:
      email: sads
      name: sada
      password: $2b$12$t1pKDQjwQ4a9zSwtomZoz.B04j3eFqnaX0X0j6rfAU7WkAbfBIYOu
    mo:
      email: malhajar@example.com
      name: mo
      password: $2b$12$BV2pemNqS//6apCr1EdpWufoCWiPF.yh2aWzSGpksORuErn7X/LR.
    mohamad:
      email: sadasd
      name: asdasd
      password: $2b$12$qikHJ4ojfbXyH/yJT9YTjOW92eI4e6dtO4Koq0C4PsaKF3y6YzZm6
    test_user:
      email: test@example.com
      name: Test User
      password: $2b$12$F1fs1RtxNh0ZIaLJqgkbX.xlavusmVLJcbuYhFGc.gPqdoMlIOAbi
preauthorized:
  emails:
  - newuser@example.com
